include: package:flutter_lints/flutter.yaml

analyze:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - prefer_const_constructors
    - prefer_relative_imports
analyzer:
  errors:
    invalid_annotation_target: ignore
